name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  DATABASE_URL: "mysql://root:rust@localhost:3306/rustdb"

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: rust
          MYSQL_DATABASE: rustdb
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build -r --verbose
    - name: Run release test
      run: cargo test -r --verbose
